name: Feature Request
description: Suggest a feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: what-and-why
    attributes:
      label: What and why?
      description: What do you want and why? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How would you solve this? (optional)
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
